### ISSUE TITLE
Support more languages

### ISSUE THREAD

**Issue by Leo310** [your-papa/obsidian-Smart2Brain#11]

**Comment by SettingDust** [comment]
Not sure if it relates to this issue. Crash at `initialAssistantMessage: la[window.localStorage.getItem("language") || "en"].initialAssistantMessage`
```
Plugin failure: smart-second-brain TypeError: Cannot read properties of undefined (reading 'initialAssistantMessage')
    at anonymous (plugin:smart-second-brain:467:3792)
    at e.<anonymous> (app.js:1:2046123)
    at app.js:1:237544
    at Object.next (app.js:1:237649)
    at a (app.js:1:236367)
```

**Comment by nicobrauchtgit** [comment]
Yeah it probably does. Could you tell me, what language you have Obsidian set to?

**Comment by timechips** [comment]
I don't know how to add a new language since I have no idea how GitHub works, but here is a Slovenian translation:
```json
{
    "general": {
        "delete": "Odstrani",
        "install": "Namesti"
    },
    "ribbon": {
        "chat": "Odpri S2B pogovor"
    },
    "cmd": {
        "chat": "Odpri pogovor",
        "pull_model": "Namesti Ollama model",
        "remove_model": "Odstrani Ollama model"
    },
    "modal": {
        "dont_show": "Ne prikaži ponovno",
        "cancel": "Prekliči",
        "confirm": "Potrdi",
        "pull_model_name": "Namesti Ollama model",
        "pull_model_desc": "Namesti model iz Ollama registra",
        "remove": {
            "name": "Odstrani Ollama model",
            "desc": "Odstrani naložen model iz tvojega sistema",
            "success": "Model odstranjen uspešno",
            "error": "Odstranjevanje modela neuspešno. Model mogoče ni naložen"
        }
    },
    "init_third_party_modal": {
        "title": "Zagon prek storitev tretjih oseb",
        "description": "Ali ste prepričani, da želite zagnati program prek tretjih oseb? Vaši osebni podatki bodo posredovani storitvam tretjih oseb, kot je OpenAI."
    },
    "notice": {
        "still_running": "Smart Second Brain še vedno deluje. Prosimo počakajte.",
        "still_indexing": "Smart Second Brain še vedno indeksira. Prosimo počakajte.",
        "ollama_not_running": "Prosimo prepričajte se da Ollama deluje preden zaženete Smart Second Brain.",
        "ollama_gen_model": "Ollama model ni nameščen. Prosimo namestite model preden zaženete Smart Second Brain.",
        "ollama_embed_model": "Ollama embed model ni nameščen. Prosimo namestite model preden zaženete Smart Second Brain.",
        "openai_key": "Prosim prepričajte se da je OpenAI API ključ veljaven preden zaženete Smart Second Brain.",
        "failed": "Neuspešni zagon Smart Second Brain-a (Error: {error}). Poskusite ponovno.",
        "failed_indexing": "Neuspešno indeksiranje smart second brain. Poskusite ponovno.",
        "done": "Smart Second Brain uspešno zagnan.",
        "error": "Pojavila se je napaka. Počakajte, da se napaka odpravi.",
        "not_initialized": "Smart Second Brain ni zagnan. Prosim zaženite.",
        "plugin_data_cleared": "Izbris podatkov Plugin-a.",
        "api_key_invalid": "API ključ ni veljaven!",
        "error_pulling_model": "Neuspešna namestitev Ollama modela (Error: {error}). Poskusite ponovno.",
        "copied_to_clipboard": "Kopiranje v odložišče:\n{text}",
        "no_notes_retrieved": "Ni bilo pridobljenih nobenih zapiskov. Morda znižajte prag podobnosti.",
        "run_failed": "Neuspešni zagon Smart Second Brain (Error: {error}). Poskusite ponovno.",
        "models_deleted": "Model {model} je bil izbrisan",
        "no_models": "Model {model} ni bil najden",
        "model_pull_canceled": "Namestitev modela preklicana"
    },
    "chat": {
        "edit": "Uredite vprašanje in regenerirajte odgovor",
        "cancel_edit": "Prekliči urejanje",
        "copy": "Kopiraj besedilo",
        "regenerate": "Izbriše vsa naslednja sporočila in regenerira odgovor na trenutno vprašanje",
        "change_assistant_prompt": "Sprememba začetnega sporočila pomočnika",
        "reset_assistant_prompt": "Ponastavitev začetnega sporočila pomočnika",
        "retrieving": "Pridobivanje",
        "reducing": "Uporabljanje {num} zapiskov",
        "stopped": "Preklicano!",
        "user": "Vi",
        "assistant": "Pomočnik",
        "save": "Shranjevanje klepeta v zapisek",
        "delete": "Brisanje zgodovine klepeta",
        "toggle_papa": "Klepetanje z uporabo zapiskov",
        "toggle_llm": "Klepet s preprostim pomočnikom",
        "stop": "Ustavi Smart Second Brain",
        "send": "Zaženi Smart Second Brain",
        "retry_error": "Prišlo je do napake. Ponovite inicializacijo",
        "reinitialize": "Ponovna vzpostavitev, spremenjene nastavitve",
        "input_placeholder": "Klepetajte s Smart Second Brain..."
    },
    "onboarding": {
        "welcome_msg": "Dobrodošli v Smart Second Brain! Vaš osebni pomočnik, ki vam z uporabo umetne inteligence pomaga pri iskanju in procesiranju vaših zapiskov.",
        "setup": "Začetna nastavitev",
        "test": "Preizkus",
        "privacy_mode_note": "Pomočnik bo deloval v načinu zasebnosti. To pomeni, da ni povezan z internetom in deluje v celoti lokalno z uporabo tehnologije Ollama.",
        "openai_mode_note": "Vaš pomočnik bo za delovanje uporabljal storitve tretjih oseb. To pomeni, da boste morali s temi storitvami deliti svoje osebne podatke, Smart Second Brain pa bo moral biti povezan z internetom, da bo lahko uporabljal velike jezikovne modele OpenAI, kot je ChatGPT..",
        "init": "Zaženi Smart Second Brain",
        "init_label": "Kliknite za začetek",
        "ollama": {
            "deamon": {
                "install": "Namestite Ollama v konzoli:",
                "set_baseurl": "Nastavitev osnovnega naslova URL od Ollame",
                "start": "Ollama zaženite tako, da v konzoli zaženete ta ukaz"
            },
            "app": {
                "download": "Prenesite aplikacijo",
                "download_link": "tukaj",
                "extract": "Izvlecite .zip in zaženite Ollama",
                "run": "Zaženite program setup.exe",
                "test_label": "Preizkusite, ali je Ollama uspešno zagnana",
                "set_origins": "V konzoli nastavite Ollama izvor, da omogočite pretakanje odgovorov:",
                "restart": "Ponovni zagon storitve Ollama ",
                "restart_label": "Kliknite ikono Ollam v menijski vrstici in jo nato zaključite ",
                "quit": "Opustite storitev Ollama ",
                "quit_label": "Kliknite ikono Ollama v menijski vrstici in nato zaključite ",
                "start_origins": "Ollama zaženite tako, da v programu powershell zaženete ta ukaz"
            },
            "test_origins": "Preizkusite, ali je izvor pravilno nastavljen",
            "install_model": "Namestite Ollama Embedding model.",
            "recommended": "Priporočeno: ",
            "set_model": "Nastavite vaš Embedding model:"
        },
        "openai": {
            "create_account": "Naredite OpenAI ",
            "create_account_link": "profil",
            "create_api_key": "Naredite ",
            "create_api_key_link": "API ključ",
            "api_key_warning": "> [!Warning] Aktivirajte API-Ključ \n> Za delovanje ključa API boste morda morali nadgraditi plačljivi račun OpenAI. To pomeni, da na svoj račun OpenAI vplačate vsaj 5 USD. To se lahko v prihodnosti spremeni.",
            "paste_api_key": "Tukaj prilepite svoj ključ:",
            "test_api_key": "Preizkusite svoj ključ API",
            "api_key_valid": "Ključ API je veljaven!"
        }
    },
    "incognito_toggle": {
        "enable": "Zaženite v svojem računalniku",
        "disable": "Izvajanje prek storitev tretjih oseb"
    },
    "settings": {
        "excludeff": "Izključitev datotek in map",
        "excludeff_desc": "Te datoteke in mape se ne bodo uporabljale za generiranje odgovorov.",
        "excludeff_add": "Dodaj",
        "excludeff_delete": "Brisanje s seznama izključenih",
        "advanced": "Napredne nastavitve",
        "clear": "Izbris podatkov plugin-a",
        "clear_desc": "S tem bodo izbrisani vsi podatki plugin-a in podatki vektorske shrambe. Na vse zapiske klepeta v vašem trezorju to ne bo vplivalo.",
        "clear_modal": {
            "title": "Izbris podatkov plugin-a",
            "description": "Ali ste prepričani da hočete izbrisati vse podatke plugin-a in podatke vektorske shrambe. Na vse zapiske klepeta v vašem trezorju to ne bo vplivalo."
        },
        "clear_label": "Počisti",
        "relaunch": "Ponovni zagon",
        "autostart": "Samodejni zagon",
        "autostart_desc": "Avtomatsko zaženi Smart Second Brain ko se odpre Obsidian.",
        "num_docs_retrieve": "Dokumenti, ki jih želite pridobiti",
        "num_docs_retrieve_desc": "Največja količina dokumentov, ki jih želite pridobiti iz trezorja. Upoštevajte, da dokumenti niso enakovredni zapiskom.",
        "debugging": "Odstranjevanje napak",
        "langsmith_key": "Langsmith API ključ",
        "langsmith_key_desc": "Zagotovite ključ API Langsmith, če želite izslediti in oceniti notranjost Smart Second Braina.",
        "verbose": "Beleženje v konzoli za razvijalce",
        "verbose_desc": "Omogočanje verbose beleženja v konzoli za razvijalce.",
        "openai": {
            "desc": " ",
            "api_key": "API ključ",
            "api_key_desc": "Navedite svoj ključ API OpenAI za uporabo velikih jezikovnih modelov od OpenAI.",
            "gen_model": "Model za klepet",
            "embed_model": "Embedding model",
            "model_descriptions": {
                "gpt-3.5-turbo": "Najnovejši GPT-3.5 Turbo model (16385 Token konteksta)",
                "gpt-4": "Najnovejši GPT-4 model (8192 Token konteksta)",
                "gpt-4-32k": "GPT-4 model (32768 Token konteksta)",
                "gpt-4-turbo": "Najnovejši GPT-4 Turbo model (128000 Token konteksta)",
                "gpt-4o": "Najnovejši GPT-4 Omni model (128000 Token konteksta)",
                "text-embedding-3-large": "Najnovejši, najzmogljivejši embedding model za angleške in neangleške naloge",
                "text-embedding-3-small": "Večja zmogljivost v primerjavi z drugo generacijo embedding modela ada",
                "text-embedding-ada-002": "Najzmogljivejši embedding model 2. generacije."
            }
        },
        "ollama": {
            "desc": " ",
            "gen_model": "Model klepeta",
            "base_url": "URL baze Ollama",
            "base_url_desc": "Nastavite URL svojege Ollame.",
            "embed_model": "Embedding model",
            "recommended": "Priporočeno",
            "other": "Ostalo",
            "model_descriptions": {
                "llama2": "Llama 2 je zbirka temeljnih jezikovnih modelov od parametrov 7B do 70B.",
                "llama2-uncensored": "Necenzurirana Llama 2 model George Sung in Jarrad Hope.",
                "mistral": "Model 7B, ki ga je izdal Mistral AI, posodobljen na različico 0.2.",
                "mistral-openorca": "Mistral OpenOrca je model s 7 milijardami parametrov, ki je bil uglašen na podlagi modela Mistral 7B z uporabo nabora podatkov OpenOrca.",
                "gemma": "Gemma je družina lahkih, najsodobnejših odprtih modelov, ki jih je ustvaril Google DeepMind.",
                "mixtral": "Visokokakovostni model mešanice strokovnjakov (MoE) z odprtimi utežmi, ki ga je izdelal Mistral AI.",
                "dolphin-mixtral": "Dolphin Mixtral (32000 Tokens)",
                "phi": "Phi-2: 2,7B jezikovni model podjetja Microsoft Research, ki izkazuje izjemne sposobnosti sklepanja in razumevanja jezika.",
                "nomic-embed-text": "Visoko zmogljiv odprt embedding model z velikim oknom konteksta.",
                "mxbai-embed-large": "Najsodobnejši veliki embedding model od mixedbread.ai."
            }
        }
    },
    "quick_settings": {
        "initialize": "Zaženi Smart Second Brain",
        "indexing_vault": "Indeksiranje trezorja",
        "time_left_minutes": "Okoli {minutes}min {seconds}s preostaja...",
        "time_left_seconds": "Okoli {seconds}s preostaja...",
        "assistant_language": "Jezik pomočnika",
        "pause_indexing": "Premor indeksiranja",
        "resume_indexing": "Nadaljevanje indeksiranja",
        "cancel_indexing": "Preklic indeksiranja",
        "retry_initialization": "Ponovni pozskus indeksiranja",
        "mode_changed": "Ponovna vzpostavitev Smart Second Brain \nwith ",
        "reinitialize": "Ponovna vzpostavitev Smart Second Brain",
        "chat_via": "Pogovarjaj se preko {model}",
        "chatview": "Moderni pregled",
        "similarity_threshold": "Podobnost",
        "creativity": "Ustvarjalnost",
        "settings_changed": "Spremenjene nastavitve.\nReinitialize Smart Second Brain.",
        "open": "Odpri hitre nastavitve",
        "close": "Zapri hitre nastavitve",
        "error": {
            "install_model": "Najprej namesti {model} model",
            "other": "Pojavila se je napaka.\nPlease ponovno zaženite..."
        }
    },
    "tooltip": {
        "creativity": "Prilagodi stopnjo izvirnosti rezultatov modela po svojih željah.",
        "similarity": "Kako podobni morajo biti pridobljeni dokumenti poizvedbi uporabnika."
    }
}
```
